version: "3"
services :
  ride_service:
    container_name: rides
    restart: always
    build: RIDES
    image: rides:latest
    ports:
      - "80:8000"
    links:
      - ride_mongodb
  ride_mongodb:
    image: "mongo"
    ports:
     - "27000:27017"
 
